import assert from "node:assert/strict";
import test from "node:test";
import { resumeAgentRuntimeAfterApproval, runAgentRuntime } from "./agentRuntime.js";
import { createAgentToolRegistry } from "./agentToolRegistry.js";
import { AI_AGENT_ACT_SYSTEM_PROMPT } from "./prompts.js";
import type { AgentCompletionResponse, AgentToolDefinition } from "./agentToolTypes.js";

function createRuntimeTestTool(name: string, result: unknown, onExecute?: () => void): AgentToolDefinition {
  return {
    name,
    description: `Test tool ${name}`,
    parameters: {
      type: "object",
      properties: {},
      additionalProperties: true
    },
    async execute() {
      onExecute?.();
      return result;
    },
    summarize(value, cached) {
      return { cached, value };
    }
  };
}

test("agent runtime keeps calling model after tool results", async () => {
  const registry = createAgentToolRegistry([createRuntimeTestTool("readFile", { filePath: "src/a.ts", content: "hello" })]);
  const requests: Record<string, unknown>[] = [];
  const responses: AgentCompletionResponse[] = [
    {
      choices: [
        {
          message: {
            role: "assistant",
            content: null,
            tool_calls: [
              {
                id: "tool-1",
                type: "function",
                function: { name: "readFile", arguments: JSON.stringify({ filePath: "src/a.ts" }) }
              }
            ]
          }
        }
      ]
    },
    {
      choices: [
        {
          message: {
            role: "assistant",
            content: "File read, ready to continue."
          }
        }
      ]
    }
  ];

  const result = await runAgentRuntime({
    userRequest: "Analyze file",
    registry,
    runId: "test-runtime-loop",
    requestCompletion: async (body) => {
      requests.push(body);
      const response = responses.shift();
      assert.ok(response);
      return response;
    }
  });

  assert.equal(result.status, "completed");
  assert.equal(result.content, "File read, ready to continue.");
  assert.equal(requests.length, 2);
  assert.equal(result.messages.at(-2)?.role, "tool");
});

test("agent runtime returns patch ids generated by tools", async () => {
  const registry = createAgentToolRegistry([
    {
      name: "proposePatch",
      description: "Generate a pending patch",
      parameters: {
        type: "object",
        properties: {},
        additionalProperties: true
      },
      async execute(_args, runtime) {
        runtime.generatedPatchIds?.push("patch-runtime-1");
        return { patchId: "patch-runtime-1" };
      },
      summarize(value, cached) {
        return { cached, value };
      }
    }
  ]);
  const responses: AgentCompletionResponse[] = [
    {
      choices: [
        {
          message: {
            role: "assistant",
            content: null,
            tool_calls: [
              {
                id: "tool-patch-1",
                type: "function",
                function: { name: "proposePatch", arguments: JSON.stringify({}) }
              }
            ]
          }
        }
      ]
    },
    {
      choices: [{ message: { role: "assistant", content: "Patch generated." } }]
    }
  ];

  const result = await runAgentRuntime({
    userRequest: "Change code",
    registry,
    runId: "test-runtime-generated-patch",
    requestCompletion: async () => {
      const response = responses.shift();
      assert.ok(response);
      return response;
    }
  });

  assert.deepEqual(result.generatedPatchIds, ["patch-runtime-1"]);
});

test("agent runtime default budget allows more than eight tool rounds", async () => {
  const registry = createAgentToolRegistry([createRuntimeTestTool("searchCode", [])]);
  const requests: Record<string, unknown>[] = [];
  let callCount = 0;

  const result = await runAgentRuntime({
    userRequest: "Search a larger codebase",
    registry,
    runId: "test-runtime-default-budget",
    requestCompletion: async (body) => {
      requests.push(body);
      callCount += 1;

      if (callCount <= 9) {
        return {
          choices: [
            {
              message: {
                role: "assistant",
                content: null,
                tool_calls: [
                  {
                    id: `tool-search-${callCount}`,
                    type: "function",
                    function: { name: "searchCode", arguments: JSON.stringify({ query: `keyword-${callCount}` }) }
                  }
                ]
              }
            }
          ]
        };
      }

      return {
        choices: [{ message: { role: "assistant", content: "Finished after extended search." } }]
      };
    }
  });

  assert.equal(result.status, "completed");
  assert.equal(result.content, "Finished after extended search.");
  assert.equal(requests.length, 10);
});

test("agent runtime warns the model before the tool budget is exhausted", async () => {
  const registry = createAgentToolRegistry([createRuntimeTestTool("searchCode", [])]);
  const requests: Record<string, unknown>[] = [];
  let callCount = 0;

  const result = await runAgentRuntime({
    userRequest: "Search until nearly limited",
    registry,
    runId: "test-runtime-budget-warning",
    maxSteps: 3,
    requestCompletion: async (body) => {
      requests.push(body);
      callCount += 1;

      if (callCount <= 2) {
        return {
          choices: [
            {
              message: {
                role: "assistant",
                content: null,
                tool_calls: [
                  {
                    id: `tool-budget-${callCount}`,
                    type: "function",
                    function: { name: "searchCode", arguments: JSON.stringify({ query: `budget-${callCount}` }) }
                  }
                ]
              }
            }
          ]
        };
      }

      return {
        choices: [{ message: { role: "assistant", content: "Stopped after warning." } }]
      };
    }
  });

  const hasBudgetWarning = requests.some((request) =>
    ((request.messages as Array<{ content?: string }> | undefined) || []).some((message) => message.content?.includes("near the tool-call limit"))
  );

  assert.equal(result.status, "completed");
  assert.equal(hasBudgetWarning, true);
});

test("agent runtime warns on repeated tool calls with the same arguments", async () => {
  const registry = createAgentToolRegistry([createRuntimeTestTool("searchCode", [])]);
  const requests: Record<string, unknown>[] = [];
  let callCount = 0;

  const result = await runAgentRuntime({
    userRequest: "Repeat search",
    registry,
    runId: "test-runtime-repeated-tool-warning",
    requestCompletion: async (body) => {
      requests.push(body);
      callCount += 1;

      if (callCount <= 2) {
        return {
          choices: [
            {
              message: {
                role: "assistant",
                content: null,
                tool_calls: [
                  {
                    id: `tool-repeat-${callCount}`,
                    type: "function",
                    function: { name: "searchCode", arguments: JSON.stringify({ query: "same-keyword" }) }
                  }
                ]
              }
            }
          ]
        };
      }

      return {
        choices: [{ message: { role: "assistant", content: "Used previous result." } }]
      };
    }
  });

  const hasRepeatedWarning = requests.some((request) =>
    ((request.messages as Array<{ content?: string }> | undefined) || []).some((message) => message.content?.includes("repeated these tool calls"))
  );

  assert.equal(result.status, "completed");
  assert.equal(hasRepeatedWarning, true);
});

test("agent runtime pauses before approval-required tools", async () => {
  let executed = false;
  const registry = createAgentToolRegistry([createRuntimeTestTool("runCommand", { exitCode: 0 }, () => (executed = true))]);
  const steps: Array<{ type: string; status?: string; actionType?: string }> = [];

  const result = await runAgentRuntime({
    userRequest: "Run tests",
    registry,
    runId: "test-runtime-approval",
    onAgentStep(step) {
      steps.push({ type: step.type, status: step.type === "approval_request" ? step.status : undefined, actionType: step.type === "approval_request" ? step.actionType : undefined });
    },
    requestCompletion: async () => ({
      choices: [
        {
          message: {
            role: "assistant",
            content: null,
            tool_calls: [
              {
                id: "tool-command-1",
                type: "function",
                function: { name: "runCommand", arguments: JSON.stringify({ command: "pnpm test" }) }
              }
            ]
          }
        }
      ]
    })
  });
  // Stop at the first approval-required tool; later tools are neither shown nor executed early.
  assert.equal(result.status, "awaiting_approval");
  assert.equal(result.pendingToolCall?.toolName, "runCommand");
  assert.equal(result.pendingToolCall?.riskLevel, "medium");
  assert.equal(executed, false);
  assert.deepEqual(steps, [{ type: "approval_request", status: "pending", actionType: "run_command" }]);
});

test("agent runtime emits no approval cards for auto-approved tools", async () => {
  const registry = createAgentToolRegistry([createRuntimeTestTool("readFile", { filePath: "src/a.ts", content: "hello" })]);
  const steps: Array<{ type: string; status?: string }> = [];
  const responses: AgentCompletionResponse[] = [
    {
      choices: [
        {
          message: {
            role: "assistant",
            content: null,
            tool_calls: [
              {
                id: "tool-read-auto",
                type: "function",
                function: { name: "readFile", arguments: JSON.stringify({ filePath: "src/a.ts" }) }
              }
            ]
          }
        }
      ]
    },
    {
      choices: [{ message: { role: "assistant", content: "Read completed." } }]
    }
  ];

  const result = await runAgentRuntime({
    userRequest: "Read a file",
    registry,
    runId: "test-runtime-auto-tool-no-approval-card",
    onAgentStep(step) {
      steps.push({ type: step.type, status: step.type === "approval_request" ? step.status : undefined });
    },
    requestCompletion: async () => {
      const response = responses.shift();
      assert.ok(response);
      return response;
    }
  });

  // Auto-approved context tools should not occupy the manual approval UI.
  assert.equal(result.status, "completed");
  assert.equal(steps.some((step) => step.type === "approval_request"), false);
});

test("agent runtime exposes only the first pending approval from a tool batch", async () => {
  let runCommandExecuted = false;
  let applyPatchExecuted = false;
  const registry = createAgentToolRegistry([
    createRuntimeTestTool("runCommand", { exitCode: 0 }, () => (runCommandExecuted = true)),
    createRuntimeTestTool("applyPatch", { files: [] }, () => (applyPatchExecuted = true))
  ]);
  const steps: Array<{ type: string; actionType?: string; status?: string }> = [];

  const result = await runAgentRuntime({
    userRequest: "Run two risky tools",
    registry,
    runId: "test-runtime-one-pending-approval",
    onAgentStep(step) {
      steps.push({ type: step.type, actionType: step.type === "approval_request" ? step.actionType : undefined, status: step.type === "approval_request" ? step.status : undefined });
    },
    requestCompletion: async () => ({
      choices: [
        {
          message: {
            role: "assistant",
            content: null,
            tool_calls: [
              {
                id: "tool-command-first",
                type: "function",
                function: { name: "runCommand", arguments: JSON.stringify({ command: "pnpm test" }) }
              },
              {
                id: "tool-patch-second",
                type: "function",
                function: { name: "applyPatch", arguments: JSON.stringify({ patchId: "patch-1" }) }
              }
            ]
          }
        }
      ]
    })
  });

  // Cline 濡炲瀛╅悧鎼佸及椤栫偘娴烽柛鎺撳椤戝洦绋夐埀顒佺▔椤忓嫮绐￠悗鍏夊墲婢规帒顔忛妷銉ュ緮閻忓繗椴稿▓蹇涘磻濠婃劗绀夐柛姘捣閻㈣顔忛妷銉ュ緮濞戞挸绉崇槐浼村箵閹邦剙顤呴悘鐐存礈閵囨岸骞嬮弽銊モ挃閻炴稑琚埀?
  assert.equal(result.status, "awaiting_approval");
  assert.equal(result.pendingToolCall?.toolName, "runCommand");
  assert.equal(runCommandExecuted, false);
  assert.equal(applyPatchExecuted, false);
  assert.deepEqual(steps, [{ type: "approval_request", actionType: "run_command", status: "pending" }]);
});

test("agent runtime feeds blocked unknown tools back to the model", async () => {
  const registry = createAgentToolRegistry([]);
  const responses: AgentCompletionResponse[] = [
    {
      choices: [
        {
          message: {
            role: "assistant",
            content: null,
            tool_calls: [
              {
                id: "unknown-tool-1",
                type: "function",
                function: { name: "missingTool", arguments: JSON.stringify({}) }
              }
            ]
          }
        }
      ]
    },
    {
      choices: [
        {
          message: {
            role: "assistant",
            content: "Cannot use that tool, so I will stop."
          }
        }
      ]
    }
  ];

  const result = await runAgentRuntime({
    userRequest: "Call unknown tool",
    registry,
    runId: "test-runtime-blocked-tool",
    requestCompletion: async () => {
      const response = responses.shift();
      assert.ok(response);
      return response;
    }
  });

  assert.equal(result.status, "completed");
  assert.match(result.messages.find((message) => message.role === "tool")?.content || "", /Unknown tool/);
  assert.equal(result.content, "Cannot use that tool, so I will stop.");
});

test("agent runtime blocks prohibited runCommand before approval", async () => {
  let executed = false;
  const registry = createAgentToolRegistry([createRuntimeTestTool("runCommand", { exitCode: 0 }, () => (executed = true))]);
  const responses: AgentCompletionResponse[] = [
    {
      choices: [
        {
          message: {
            role: "assistant",
            content: null,
            tool_calls: [
              {
                id: "tool-command-blocked",
                type: "function",
                function: { name: "runCommand", arguments: JSON.stringify({ command: "rm -rf dist" }) }
              }
            ]
          }
        }
      ]
    },
    {
      choices: [
        {
          message: {
            role: "assistant",
            content: "Command was blocked, so I will not run it."
          }
        }
      ]
    }
  ];

  const result = await runAgentRuntime({
    userRequest: "Run dangerous command",
    registry,
    runId: "test-runtime-blocked-command",
    requestCompletion: async () => {
      const response = responses.shift();
      assert.ok(response);
      return response;
    }
  });

  assert.equal(executed, false);
  assert.equal(result.status, "completed");
  assert.match(result.messages.find((message) => message.role === "tool")?.content || "", /blocked pattern/);
  assert.equal(result.content, "Command was blocked, so I will not run it.");
});

test("agent runtime resumes after approving a pending tool call", async () => {
  let executed = false;
  const registry = createAgentToolRegistry([createRuntimeTestTool("runCommand", { exitCode: 0 }, () => (executed = true))]);
  const result = await resumeAgentRuntimeAfterApproval({
    userRequest: "Run tests",
    registry,
    runId: "test-runtime-resume-approved",
    pendingToolCall: {
      actionId: "run_command:test-action",
      toolCallId: "tool-command-1",
      toolName: "runCommand",
      arguments: { command: "pnpm test" },
      riskLevel: "medium",
      status: "pending",
      createdAt: Date.now()
    },
    persistedMessages: [
      {
        id: "assistant-tool-call",
        role: "assistant",
        content: null,
        toolCalls: [{ id: "tool-command-1", name: "runCommand", arguments: { command: "pnpm test" } }],
        createdAt: Date.now()
      }
    ],
    decision: "approved",
    requestCompletion: async () => ({
      choices: [{ message: { role: "assistant", content: "Command result handled." } }]
    })
  });

  assert.equal(executed, true);
  assert.equal(result.status, "completed");
  assert.equal(result.content, "Command result handled.");
  assert.equal(result.messages.some((message) => message.role === "tool" && /exitCode/.test(message.content || "")), true);
});

test("agent runtime resumes after rejecting a pending tool call", async () => {
  let executed = false;
  const registry = createAgentToolRegistry([createRuntimeTestTool("runCommand", { exitCode: 0 }, () => (executed = true))]);
  const result = await resumeAgentRuntimeAfterApproval({
    userRequest: "Run tests",
    registry,
    runId: "test-runtime-resume-rejected",
    pendingToolCall: {
      actionId: "run_command:test-action",
      toolCallId: "tool-command-1",
      toolName: "runCommand",
      arguments: { command: "pnpm test" },
      riskLevel: "medium",
      status: "pending",
      createdAt: Date.now()
    },
    persistedMessages: [
      {
        id: "assistant-tool-call",
        role: "assistant",
        content: null,
        toolCalls: [{ id: "tool-command-1", name: "runCommand", arguments: { command: "pnpm test" } }],
        createdAt: Date.now()
      }
    ],
    decision: "rejected",
    requestCompletion: async () => ({
      choices: [{ message: { role: "assistant", content: "I will continue without that command." } }]
    })
  });

  assert.equal(executed, false);
  assert.equal(result.status, "completed");
  assert.equal(result.content, "I will continue without that command.");
  assert.match(result.messages.find((message) => message.role === "tool")?.content || "", /rejected/);
});

test("agent runtime stops when tool-call step limit is reached", async () => {
  const registry = createAgentToolRegistry([createRuntimeTestTool("searchCode", [])]);

  const result = await runAgentRuntime({
    userRequest: "Search code",
    registry,
    runId: "test-runtime-limit",
    maxSteps: 2,
    requestCompletion: async () => ({
      choices: [
        {
          message: {
            role: "assistant",
            content: null,
            tool_calls: [
              {
                id: `tool-${Date.now()}-${Math.random()}`,
                type: "function",
                function: { name: "searchCode", arguments: JSON.stringify({ query: "Agent" }) }
              }
            ]
          }
        }
      ]
    })
  });

  assert.equal(result.status, "step_limit_reached");
  assert.match(result.content, /tool-call limit/);
});

test("plan mode exposes only readonly tools to the model", async () => {
  const requests: Record<string, unknown>[] = [];

  const result = await runAgentRuntime({
    userRequest: "Plan a change",
    runId: "test-runtime-plan-mode",
    mode: "plan",
    requestCompletion: async (body) => {
      requests.push(body);
      return {
        choices: [{ message: { role: "assistant", content: "Plan completed." } }]
      };
    }
  });

  const toolNames = ((requests[0].tools as Array<{ function: { name: string } }>) || []).map((tool) => tool.function.name);
  assert.equal(result.status, "completed");
  assert.deepEqual(toolNames.sort(), ["inspectProject", "readFile", "readFileRange", "searchCode"].sort());
});

test("act mode exposes edit, patch, and command tools to the model", async () => {
  const requests: Record<string, unknown>[] = [];

  const result = await runAgentRuntime({
    userRequest: "Implement a change",
    runId: "test-runtime-act-mode",
    mode: "act",
    requestCompletion: async (body) => {
      requests.push(body);
      return {
        choices: [{ message: { role: "assistant", content: "Act completed." } }]
      };
    }
  });

  const toolNames = ((requests[0].tools as Array<{ function: { name: string } }>) || []).map((tool) => tool.function.name);
  assert.equal(result.status, "completed");
  assert.equal(toolNames.includes("replaceInFile"), true);
  assert.equal(toolNames.includes("writeFile"), true);
  assert.equal(toolNames.includes("proposePatch"), true);
  assert.equal(toolNames.includes("applyPatch"), true);
  assert.equal(toolNames.includes("runCommand"), true);
  // 直接编辑工具排在旧 patch 工具前面，引导模型优先走工具式编辑链路。
  assert.ok(toolNames.indexOf("replaceInFile") < toolNames.indexOf("proposePatch"));
  assert.ok(toolNames.indexOf("writeFile") < toolNames.indexOf("proposePatch"));
});

test("act prompt 优先引导工具式文件编辑", () => {
  assert.match(AI_AGENT_ACT_SYSTEM_PROMPT, /use replaceInFile as the default editing path/i);
  assert.match(AI_AGENT_ACT_SYSTEM_PROMPT, /Use writeFile only when creating a new file/i);
  assert.match(AI_AGENT_ACT_SYSTEM_PROMPT, /treat finalContent from the tool result as the latest source of truth/i);
  assert.match(AI_AGENT_ACT_SYSTEM_PROMPT, /Use proposePatch only when the user explicitly asks/i);
});

test("agent runtime budget warning keeps direct edit tools as the preferred path", async () => {
  const registry = createAgentToolRegistry([createRuntimeTestTool("searchCode", [])]);
  const requests: Record<string, unknown>[] = [];
  let callCount = 0;

  const result = await runAgentRuntime({
    userRequest: "Modify code",
    registry,
    runId: "test-runtime-budget-warning-direct-edit",
    maxSteps: 3,
    requestCompletion: async (body) => {
      requests.push(body);
      callCount += 1;

      if (callCount <= 2) {
        return {
          choices: [
            {
              message: {
                role: "assistant",
                content: null,
                tool_calls: [
                  {
                    id: `tool-direct-edit-budget-${callCount}`,
                    type: "function",
                    function: { name: "searchCode", arguments: JSON.stringify({ query: `edit-${callCount}` }) }
                  }
                ]
              }
            }
          ]
        };
      }

      return {
        choices: [{ message: { role: "assistant", content: "Stopped after direct edit warning." } }]
      };
    }
  });

  const warningMessages = requests.flatMap((request) => (request.messages as Array<{ content?: string }> | undefined) || []).filter((message) => message.content?.includes("near the tool-call limit"));
  assert.equal(result.status, "completed");
  assert.equal(warningMessages.some((message) => message.content?.includes("replaceInFile")), true);
  assert.equal(warningMessages.some((message) => message.content?.includes("writeFile")), true);
  assert.equal(warningMessages.some((message) => message.content?.includes("proposePatch only when")), true);
});

test("agent runtime repeated-tool warning asks the model to move to direct edit tools", async () => {
  const registry = createAgentToolRegistry([createRuntimeTestTool("searchCode", [])]);
  const requests: Record<string, unknown>[] = [];
  let callCount = 0;

  const result = await runAgentRuntime({
    userRequest: "Repeat then edit",
    registry,
    runId: "test-runtime-repeated-warning-direct-edit",
    requestCompletion: async (body) => {
      requests.push(body);
      callCount += 1;

      if (callCount <= 2) {
        return {
          choices: [
            {
              message: {
                role: "assistant",
                content: null,
                tool_calls: [
                  {
                    id: `tool-direct-edit-repeat-${callCount}`,
                    type: "function",
                    function: { name: "searchCode", arguments: JSON.stringify({ query: "same-edit-keyword" }) }
                  }
                ]
              }
            }
          ]
        };
      }

      return {
        choices: [{ message: { role: "assistant", content: "Used direct edit warning." } }]
      };
    }
  });

  const warningMessages = requests.flatMap((request) => (request.messages as Array<{ content?: string }> | undefined) || []).filter((message) => message.content?.includes("repeated these tool calls"));
  assert.equal(result.status, "completed");
  assert.equal(warningMessages.some((message) => message.content?.includes("replaceInFile/writeFile")), true);
  assert.equal(warningMessages.some((message) => message.content?.includes("proposePatch only when")), true);
});
