import assert from "node:assert/strict";
import test from "node:test";
import { resumeAgentRuntimeAfterApproval, runAgentRuntime } from "./agentRuntime.js";
import { createAgentToolRegistry } from "./agentToolRegistry.js";
import { AI_AGENT_ACT_SYSTEM_PROMPT } from "./prompts.js";
import type { AgentCompletionResponse, AgentToolDefinition, AgentToolRuntime } from "./agentToolTypes.js";
import type { AgentStep } from "./types.js";
import { createTaskWorkflow } from "./taskWorkflow/index.js";

function createRuntimeTestTool(name: string, result: unknown, onExecute?: (runtime: AgentToolRuntime) => void): AgentToolDefinition {
  return {
    name,
    description: `Test tool ${name}`,
    parameters: {
      type: "object",
      properties: {},
      additionalProperties: true
    },
    async execute(_args, runtime) {
      onExecute?.(runtime);
      return result;
    },
    summarize(value, cached) {
      return { cached, value };
    }
  };
}

test("agent runtime keeps calling model after tool results", async () => {
  const registry = createAgentToolRegistry([createRuntimeTestTool("readFile", { filePath: "src/a.ts", content: "hello" })]);
  const requests: Record<string, unknown>[] = [];
  const responses: AgentCompletionResponse[] = [
    {
      choices: [
        {
          message: {
            role: "assistant",
            content: null,
            tool_calls: [
              {
                id: "tool-1",
                type: "function",
                function: { name: "readFile", arguments: JSON.stringify({ filePath: "src/a.ts" }) }
              }
            ]
          }
        }
      ]
    },
    {
      choices: [
        {
          message: {
            role: "assistant",
            content: "File read, ready to continue."
          }
        }
      ]
    }
  ];

  const result = await runAgentRuntime({
    userRequest: "Analyze file",
    projectMemoryPrompt: "PROJECT_MEMORY_SENTINEL",
    registry,
    runId: "test-runtime-loop",
    requestCompletion: async (body) => {
      requests.push(body);
      const response = responses.shift();
      assert.ok(response);
      return response;
    }
  });

  assert.equal(result.status, "completed");
  assert.equal(result.content, "File read, ready to continue.");
  assert.equal(requests.length, 2);
  assert.equal(result.messages.at(-2)?.role, "tool");
  const firstMessages = requests[0]?.messages as Array<{ role: string; content: string }>;
  assert.match(firstMessages[0]?.content || "", /PROJECT_MEMORY_SENTINEL/);
});

test("agent runtime returns patch ids generated by tools", async () => {
  const registry = createAgentToolRegistry([
    {
      name: "proposePatch",
      description: "Generate a pending patch",
      parameters: {
        type: "object",
        properties: {},
        additionalProperties: true
      },
      async execute(_args, runtime) {
        runtime.generatedPatchIds?.push("patch-runtime-1");
        return { patchId: "patch-runtime-1" };
      },
      summarize(value, cached) {
        return { cached, value };
      }
    }
  ]);
  const responses: AgentCompletionResponse[] = [
    {
      choices: [
        {
          message: {
            role: "assistant",
            content: null,
            tool_calls: [
              {
                id: "tool-patch-1",
                type: "function",
                function: { name: "proposePatch", arguments: JSON.stringify({}) }
              }
            ]
          }
        }
      ]
    },
    {
      choices: [{ message: { role: "assistant", content: "Patch generated." } }]
    }
  ];

  const result = await runAgentRuntime({
    userRequest: "Change code",
    registry,
    runId: "test-runtime-generated-patch",
    requestCompletion: async () => {
      const response = responses.shift();
      assert.ok(response);
      return response;
    }
  });

  assert.deepEqual(result.generatedPatchIds, ["patch-runtime-1"]);
});

test("agent runtime direct edit tools do not create pending patch ids", async () => {
  const registry = createAgentToolRegistry([
    {
      name: "replaceInFile",
      description: "Directly edit a file",
      parameters: {
        type: "object",
        properties: {},
        additionalProperties: true
      },
      async execute() {
        // 直写工具代表第五阶段主链路：文件已经由工具落盘，不再生成待审 patch。
        return {
          filePath: "src/app.ts",
          changed: true,
          replacements: 1,
          oldContentPreview: "const title = 'old';",
          finalContent: "const title = 'new';",
          checkpointId: "checkpoint-direct-1"
        };
      },
      summarize(value, cached) {
        return { cached, value };
      }
    }
  ]);
  const responses: AgentCompletionResponse[] = [
    {
      choices: [
        {
          message: {
            role: "assistant",
            content: null,
            tool_calls: [
              {
                id: "tool-direct-edit-1",
                type: "function",
                function: { name: "replaceInFile", arguments: JSON.stringify({ filePath: "src/app.ts", search: "old", replace: "new" }) }
              }
            ]
          }
        }
      ]
    },
    {
      choices: [{ message: { role: "assistant", content: "已直接修改文件。" } }]
    }
  ];

  const result = await runAgentRuntime({
    userRequest: "修改标题",
    registry,
    runId: "test-runtime-direct-edit-no-patch",
    mode: "act",
    requestCompletion: async () => {
      const response = responses.shift();
      assert.ok(response);
      return response;
    }
  });

  assert.equal(result.status, "completed");
  assert.deepEqual(result.generatedPatchIds, []);
  assert.match(result.messages.find((message) => message.role === "tool")?.content || "", /finalContent/);
});

test("agent runtime default budget allows more than eight tool rounds", async () => {
  const registry = createAgentToolRegistry([createRuntimeTestTool("searchCode", [])]);
  const requests: Record<string, unknown>[] = [];
  let callCount = 0;

  const result = await runAgentRuntime({
    userRequest: "Search a larger codebase",
    registry,
    runId: "test-runtime-default-budget",
    requestCompletion: async (body) => {
      requests.push(body);
      callCount += 1;

      if (callCount <= 9) {
        return {
          choices: [
            {
              message: {
                role: "assistant",
                content: null,
                tool_calls: [
                  {
                    id: `tool-search-${callCount}`,
                    type: "function",
                    function: { name: "searchCode", arguments: JSON.stringify({ query: `keyword-${callCount}` }) }
                  }
                ]
              }
            }
          ]
        };
      }

      return {
        choices: [{ message: { role: "assistant", content: "Finished after extended search." } }]
      };
    }
  });

  assert.equal(result.status, "completed");
  assert.equal(result.content, "Finished after extended search.");
  assert.equal(requests.length, 10);
});

test("agent runtime warns the model before the tool budget is exhausted", async () => {
  const registry = createAgentToolRegistry([createRuntimeTestTool("searchCode", [])]);
  const requests: Record<string, unknown>[] = [];
  let callCount = 0;

  const result = await runAgentRuntime({
    userRequest: "Search until nearly limited",
    registry,
    runId: "test-runtime-budget-warning",
    maxSteps: 3,
    requestCompletion: async (body) => {
      requests.push(body);
      callCount += 1;

      if (callCount <= 2) {
        return {
          choices: [
            {
              message: {
                role: "assistant",
                content: null,
                tool_calls: [
                  {
                    id: `tool-budget-${callCount}`,
                    type: "function",
                    function: { name: "searchCode", arguments: JSON.stringify({ query: `budget-${callCount}` }) }
                  }
                ]
              }
            }
          ]
        };
      }

      return {
        choices: [{ message: { role: "assistant", content: "Stopped after warning." } }]
      };
    }
  });

  const hasBudgetWarning = requests.some((request) =>
    ((request.messages as Array<{ content?: string }> | undefined) || []).some((message) => message.content?.includes("near the tool-call limit"))
  );

  assert.equal(result.status, "completed");
  assert.equal(hasBudgetWarning, true);
});

test("agent runtime warns on repeated tool calls with the same arguments", async () => {
  const registry = createAgentToolRegistry([createRuntimeTestTool("searchCode", [])]);
  const requests: Record<string, unknown>[] = [];
  let callCount = 0;

  const result = await runAgentRuntime({
    userRequest: "Repeat search",
    registry,
    runId: "test-runtime-repeated-tool-warning",
    requestCompletion: async (body) => {
      requests.push(body);
      callCount += 1;

      if (callCount <= 2) {
        return {
          choices: [
            {
              message: {
                role: "assistant",
                content: null,
                tool_calls: [
                  {
                    id: `tool-repeat-${callCount}`,
                    type: "function",
                    function: { name: "searchCode", arguments: JSON.stringify({ query: "same-keyword" }) }
                  }
                ]
              }
            }
          ]
        };
      }

      return {
        choices: [{ message: { role: "assistant", content: "Used previous result." } }]
      };
    }
  });

  const hasRepeatedWarning = requests.some((request) =>
    ((request.messages as Array<{ content?: string }> | undefined) || []).some((message) => message.content?.includes("repeated these tool calls"))
  );

  assert.equal(result.status, "completed");
  assert.equal(hasRepeatedWarning, true);
});

test("agent runtime pauses before approval-required tools", async () => {
  let executed = false;
  const registry = createAgentToolRegistry([createRuntimeTestTool("runCommand", { exitCode: 0 }, () => (executed = true))]);
  const steps: Array<{ type: string; status?: string; actionType?: string }> = [];

  const result = await runAgentRuntime({
    userRequest: "Run tests",
    registry,
    runId: "test-runtime-approval",
    agentContext: { userGoal: "Run tests", filesRead: ["src/service.ts"], searchQueries: [], searchResultFiles: [], relevantFiles: ["src/service.ts"] },
    onAgentStep(step) {
      steps.push({ type: step.type, status: step.type === "approval_request" ? step.status : undefined, actionType: step.type === "approval_request" ? step.actionType : undefined });
    },
    requestCompletion: async () => ({
      choices: [
        {
          message: {
            role: "assistant",
            content: null,
            tool_calls: [
              {
                id: "tool-command-1",
                type: "function",
                function: { name: "runCommand", arguments: JSON.stringify({ command: "pnpm test" }) }
              }
            ]
          }
        }
      ]
    })
  });
  // Stop at the first approval-required tool; later tools are neither shown nor executed early.
  assert.equal(result.status, "awaiting_approval");
  assert.equal(result.pendingToolCall?.toolName, "runCommand");
  assert.equal(result.pendingToolCall?.riskLevel, "medium");
  assert.deepEqual(result.pendingToolCall?.agentContext?.filesRead, ["src/service.ts"]);
  assert.equal(executed, false);
  assert.deepEqual(steps, [{ type: "approval_request", status: "pending", actionType: "run_command" }]);
});

test("agent runtime emits no approval cards for auto-approved tools", async () => {
  const registry = createAgentToolRegistry([createRuntimeTestTool("readFile", { filePath: "src/a.ts", content: "hello" })]);
  const steps: Array<{ type: string; status?: string }> = [];
  const responses: AgentCompletionResponse[] = [
    {
      choices: [
        {
          message: {
            role: "assistant",
            content: null,
            tool_calls: [
              {
                id: "tool-read-auto",
                type: "function",
                function: { name: "readFile", arguments: JSON.stringify({ filePath: "src/a.ts" }) }
              }
            ]
          }
        }
      ]
    },
    {
      choices: [{ message: { role: "assistant", content: "Read completed." } }]
    }
  ];

  const result = await runAgentRuntime({
    userRequest: "Read a file",
    registry,
    runId: "test-runtime-auto-tool-no-approval-card",
    onAgentStep(step) {
      steps.push({ type: step.type, status: step.type === "approval_request" ? step.status : undefined });
    },
    requestCompletion: async () => {
      const response = responses.shift();
      assert.ok(response);
      return response;
    }
  });

  // Auto-approved context tools should not occupy the manual approval UI.
  assert.equal(result.status, "completed");
  assert.equal(steps.some((step) => step.type === "approval_request"), false);
});

test("agent runtime exposes only the first pending approval from a tool batch", async () => {
  let runCommandExecuted = false;
  let applyPatchExecuted = false;
  const registry = createAgentToolRegistry([
    createRuntimeTestTool("runCommand", { exitCode: 0 }, () => (runCommandExecuted = true)),
    createRuntimeTestTool("applyPatch", { files: [] }, () => (applyPatchExecuted = true))
  ]);
  const steps: Array<{ type: string; actionType?: string; status?: string }> = [];

  const result = await runAgentRuntime({
    userRequest: "Run two risky tools",
    registry,
    runId: "test-runtime-one-pending-approval",
    onAgentStep(step) {
      steps.push({ type: step.type, actionType: step.type === "approval_request" ? step.actionType : undefined, status: step.type === "approval_request" ? step.status : undefined });
    },
    requestCompletion: async () => ({
      choices: [
        {
          message: {
            role: "assistant",
            content: null,
            tool_calls: [
              {
                id: "tool-command-first",
                type: "function",
                function: { name: "runCommand", arguments: JSON.stringify({ command: "pnpm test" }) }
              },
              {
                id: "tool-patch-second",
                type: "function",
                function: { name: "applyPatch", arguments: JSON.stringify({ patchId: "patch-1" }) }
              }
            ]
          }
        }
      ]
    })
  });

  // Cline 濡炲瀛╅悧鎼佸及椤栫偘娴烽柛鎺撳椤戝洦绋夐埀顒佺▔椤忓嫮绐￠悗鍏夊墲婢规帒顔忛妷銉ュ緮閻忓繗椴稿▓蹇涘磻濠婃劗绀夐柛姘捣閻㈣顔忛妷銉ュ緮濞戞挸绉崇槐浼村箵閹邦剙顤呴悘鐐存礈閵囨岸骞嬮弽銊モ挃閻炴稑琚埀?
  assert.equal(result.status, "awaiting_approval");
  assert.equal(result.pendingToolCall?.toolName, "runCommand");
  assert.equal(runCommandExecuted, false);
  assert.equal(applyPatchExecuted, false);
  assert.deepEqual(steps, [{ type: "approval_request", actionType: "run_command", status: "pending" }]);
});

test("agent runtime feeds blocked unknown tools back to the model", async () => {
  const registry = createAgentToolRegistry([]);
  const responses: AgentCompletionResponse[] = [
    {
      choices: [
        {
          message: {
            role: "assistant",
            content: null,
            tool_calls: [
              {
                id: "unknown-tool-1",
                type: "function",
                function: { name: "missingTool", arguments: JSON.stringify({}) }
              }
            ]
          }
        }
      ]
    },
    {
      choices: [
        {
          message: {
            role: "assistant",
            content: "Cannot use that tool, so I will stop."
          }
        }
      ]
    }
  ];

  const result = await runAgentRuntime({
    userRequest: "Call unknown tool",
    registry,
    runId: "test-runtime-blocked-tool",
    requestCompletion: async () => {
      const response = responses.shift();
      assert.ok(response);
      return response;
    }
  });

  assert.equal(result.status, "completed");
  assert.match(result.messages.find((message) => message.role === "tool")?.content || "", /Unknown tool/);
  assert.equal(result.content, "Cannot use that tool, so I will stop.");
});

test("agent runtime blocks prohibited runCommand before approval", async () => {
  let executed = false;
  const registry = createAgentToolRegistry([createRuntimeTestTool("runCommand", { exitCode: 0 }, () => (executed = true))]);
  const responses: AgentCompletionResponse[] = [
    {
      choices: [
        {
          message: {
            role: "assistant",
            content: null,
            tool_calls: [
              {
                id: "tool-command-blocked",
                type: "function",
                function: { name: "runCommand", arguments: JSON.stringify({ command: "rm -rf dist" }) }
              }
            ]
          }
        }
      ]
    },
    {
      choices: [
        {
          message: {
            role: "assistant",
            content: "Command was blocked, so I will not run it."
          }
        }
      ]
    }
  ];

  const result = await runAgentRuntime({
    userRequest: "Run dangerous command",
    registry,
    runId: "test-runtime-blocked-command",
    requestCompletion: async () => {
      const response = responses.shift();
      assert.ok(response);
      return response;
    }
  });

  assert.equal(executed, false);
  assert.equal(result.status, "completed");
  assert.match(result.messages.find((message) => message.role === "tool")?.content || "", /blocked pattern/);
  assert.equal(result.content, "Command was blocked, so I will not run it.");
});

test("agent runtime resumes after approving a pending tool call", async () => {
  let executed = false;
  const registry = createAgentToolRegistry([createRuntimeTestTool("runCommand", { exitCode: 0 }, () => (executed = true))]);
  const result = await resumeAgentRuntimeAfterApproval({
    userRequest: "Run tests",
    registry,
    runId: "test-runtime-resume-approved",
    pendingToolCall: {
      actionId: "run_command:test-action",
      toolCallId: "tool-command-1",
      toolName: "runCommand",
      arguments: { command: "pnpm test" },
      riskLevel: "medium",
      status: "pending",
      createdAt: Date.now()
    },
    persistedMessages: [
      {
        id: "assistant-tool-call",
        role: "assistant",
        content: null,
        toolCalls: [{ id: "tool-command-1", name: "runCommand", arguments: { command: "pnpm test" } }],
        createdAt: Date.now()
      }
    ],
    decision: "approved",
    requestCompletion: async () => ({
      choices: [{ message: { role: "assistant", content: "Command result handled." } }]
    })
  });

  assert.equal(executed, true);
  assert.equal(result.status, "completed");
  assert.equal(result.content, "Command result handled.");
  assert.equal(result.messages.some((message) => message.role === "tool" && /exitCode/.test(message.content || "")), true);
});

test("agent runtime resumes after rejecting a pending tool call", async () => {
  let executed = false;
  const registry = createAgentToolRegistry([createRuntimeTestTool("runCommand", { exitCode: 0 }, () => (executed = true))]);
  const result = await resumeAgentRuntimeAfterApproval({
    userRequest: "Run tests",
    registry,
    runId: "test-runtime-resume-rejected",
    pendingToolCall: {
      actionId: "run_command:test-action",
      toolCallId: "tool-command-1",
      toolName: "runCommand",
      arguments: { command: "pnpm test" },
      riskLevel: "medium",
      status: "pending",
      createdAt: Date.now()
    },
    persistedMessages: [
      {
        id: "assistant-tool-call",
        role: "assistant",
        content: null,
        toolCalls: [{ id: "tool-command-1", name: "runCommand", arguments: { command: "pnpm test" } }],
        createdAt: Date.now()
      }
    ],
    decision: "rejected",
    requestCompletion: async () => ({
      choices: [{ message: { role: "assistant", content: "I will continue without that command." } }]
    })
  });

  assert.equal(executed, false);
  assert.equal(result.status, "completed");
  assert.equal(result.content, "I will continue without that command.");
  assert.match(result.messages.find((message) => message.role === "tool")?.content || "", /rejected/);
});

test("agent runtime stops when tool-call step limit is reached", async () => {
  const registry = createAgentToolRegistry([createRuntimeTestTool("searchCode", [])]);
  const steps: AgentStep[] = [];

  const result = await runAgentRuntime({
    userRequest: "Search code",
    registry,
    runId: "test-runtime-limit",
    maxSteps: 2,
    onAgentStep(step) {
      steps.push(step);
    },
    requestCompletion: async () => ({
      choices: [
        {
          message: {
            role: "assistant",
            content: null,
            tool_calls: [
              {
                id: `tool-${Date.now()}-${Math.random()}`,
                type: "function",
                function: { name: "searchCode", arguments: JSON.stringify({ query: "Agent" }) }
              }
            ]
          }
        }
      ]
    })
  });

  assert.equal(result.status, "step_limit_reached");
  assert.match(result.content, /tool-call limit/);
  assert.equal(steps.some((step) => step.type === "error" && step.message.includes("Tool budget limit reached")), true);
});

test("agent runtime restores Safe Editor context after approval", async () => {
  let restoredFilesRead: string[] = [];
  const registry = createAgentToolRegistry([createRuntimeTestTool("runCommand", { exitCode: 0 }, (runtime) => { restoredFilesRead = runtime.agentContext.filesRead; })]);
  await resumeAgentRuntimeAfterApproval({
    userRequest: "Run tests",
    registry,
    pendingToolCall: {
      actionId: "run_command:restore-context", toolCallId: "tool-restore-context", toolName: "runCommand", arguments: { command: "pnpm test" }, riskLevel: "medium", status: "pending", createdAt: Date.now(),
      agentContext: { userGoal: "Run tests", filesRead: ["src/service.ts"], searchQueries: ["impact:src/service.ts"], searchResultFiles: [], relevantFiles: ["src/service.ts"] }
    },
    decision: "approved",
    requestCompletion: async () => ({ choices: [{ message: { role: "assistant", content: "done" } }] })
  });

  assert.deepEqual(restoredFilesRead, ["src/service.ts"]);
});

test("agent runtime emits a visible budget warning step before exhausting tool budget", async () => {
  const registry = createAgentToolRegistry([createRuntimeTestTool("searchCode", [])]);
  const steps: AgentStep[] = [];

  await runAgentRuntime({
    userRequest: "Search until budget warning",
    registry,
    runId: "test-runtime-visible-budget-warning",
    maxSteps: 4,
    onAgentStep(step) {
      steps.push(step);
    },
    requestCompletion: async () => ({
      choices: [
        {
          message: {
            role: "assistant",
            content: null,
            tool_calls: [
              {
                id: `tool-budget-visible-${Date.now()}-${Math.random()}`,
                type: "function",
                function: { name: "searchCode", arguments: JSON.stringify({ query: "Agent" }) }
              }
            ]
          }
        }
      ]
    })
  });

  assert.equal(steps.some((step) => step.type === "message" && step.content.includes("Tool budget warning")), true);
});

test("plan mode exposes only readonly tools to the model", async () => {
  const requests: Record<string, unknown>[] = [];

  const result = await runAgentRuntime({
    userRequest: "Plan a change",
    runId: "test-runtime-plan-mode",
    mode: "plan",
    requestCompletion: async (body) => {
      requests.push(body);
      return {
        choices: [{ message: { role: "assistant", content: "Plan completed." } }]
      };
    }
  });

  const toolNames = ((requests[0].tools as Array<{ function: { name: string } }>) || []).map((tool) => tool.function.name);
  assert.equal(result.status, "completed");
  // Symbol Graph 和 External Context Gateway 都是只读上下文能力，因此规划模式也应允许使用。
  assert.deepEqual(toolNames.sort(), ["analyzeImpact", "analyzeSymbolGraph", "browseWebPage", "checkExistence", "fetchApiDocs", "findSimilarPatterns", "getExternalContextStatus", "inspectProject", "listCodeDefinitionNames", "listFiles", "readFile", "readFileChunk", "readFileRange", "searchCode", "searchCodeRegex", "searchFilesByName", "searchOfficialDocs", "searchWeb", "sequenceReasoning"].sort());
});

test("act mode exposes edit, patch, and command tools to the model", async () => {
  const requests: Record<string, unknown>[] = [];

  const result = await runAgentRuntime({
    userRequest: "Implement a change",
    runId: "test-runtime-act-mode",
    mode: "act",
    requestCompletion: async (body) => {
      requests.push(body);
      return {
        choices: [{ message: { role: "assistant", content: "Act completed." } }]
      };
    }
  });

  const toolNames = ((requests[0].tools as Array<{ function: { name: string } }>) || []).map((tool) => tool.function.name);
  assert.equal(result.status, "completed");
  assert.equal(toolNames.includes("replaceInFile"), true);
  assert.equal(toolNames.includes("writeFile"), true);
  assert.equal(toolNames.includes("proposePatch"), true);
  assert.equal(toolNames.includes("applyPatch"), true);
  assert.equal(toolNames.includes("runCommand"), true);
  assert.equal(toolNames.includes("automateBrowser"), true);
  // patch 工具排在直接编辑工具前面，引导常规修改先进入 diff 审核。
  assert.ok(toolNames.indexOf("proposePatch") < toolNames.indexOf("replaceInFile"));
  assert.ok(toolNames.indexOf("applyPatch") < toolNames.indexOf("writeFile"));
});

test("act mode blocks edits until Pattern Finder has been called", async () => {
  let requestCount = 0;
  const result = await runAgentRuntime({
    userRequest: "实现一个新服务",
    runId: "test-runtime-pattern-finder-gate",
    mode: "act",
    requestCompletion: async () => {
      requestCount += 1;
      return requestCount === 1
        ? { choices: [{ message: { role: "assistant", tool_calls: [{ id: "patch-before-pattern", type: "function", function: { name: "proposePatch", arguments: "{}" } }] } }] }
        : { choices: [{ message: { role: "assistant", content: "已收到检索要求。" } }] };
    }
  });

  const blockedToolMessage = result.messages.find((message) => message.role === "tool" && message.toolCallId === "patch-before-pattern");
  assert.match(blockedToolMessage?.content || "", /findSimilarPatterns/);
});

test("act prompt 优先引导生成可审查 patch", () => {
  assert.match(AI_AGENT_ACT_SYSTEM_PROMPT, /use proposePatch as the default path/i);
  assert.match(AI_AGENT_ACT_SYSTEM_PROMPT, /inspect the diff before applying changes/i);
  assert.match(AI_AGENT_ACT_SYSTEM_PROMPT, /Use replaceInFile only when the user explicitly asks for direct edits/i);
  assert.match(AI_AGENT_ACT_SYSTEM_PROMPT, /treat finalContent from the tool result as the latest source of truth/i);
  assert.match(AI_AGENT_ACT_SYSTEM_PROMPT, /Use proposePatch for reviewable code changes before files are written/i);
});

test("agent runtime budget warning keeps patch review as the preferred path", async () => {
  const registry = createAgentToolRegistry([createRuntimeTestTool("searchCode", [])]);
  const requests: Record<string, unknown>[] = [];
  let callCount = 0;

  const result = await runAgentRuntime({
    userRequest: "Modify code",
    registry,
    runId: "test-runtime-budget-warning-direct-edit",
    maxSteps: 3,
    requestCompletion: async (body) => {
      requests.push(body);
      callCount += 1;

      if (callCount <= 2) {
        return {
          choices: [
            {
              message: {
                role: "assistant",
                content: null,
                tool_calls: [
                  {
                    id: `tool-direct-edit-budget-${callCount}`,
                    type: "function",
                    function: { name: "searchCode", arguments: JSON.stringify({ query: `edit-${callCount}` }) }
                  }
                ]
              }
            }
          ]
        };
      }

      return {
        choices: [{ message: { role: "assistant", content: "Stopped after direct edit warning." } }]
      };
    }
  });

  const warningMessages = requests.flatMap((request) => (request.messages as Array<{ content?: string }> | undefined) || []).filter((message) => message.content?.includes("near the tool-call limit"));
  assert.equal(result.status, "completed");
  assert.equal(warningMessages.some((message) => message.content?.includes("use proposePatch")), true);
  assert.equal(warningMessages.some((message) => message.content?.includes("reviewable pending patch")), true);
  assert.equal(warningMessages.some((message) => message.content?.includes("replaceInFile/writeFile only")), true);
});

test("agent runtime repeated-tool warning asks the model to move to patch review", async () => {
  const registry = createAgentToolRegistry([createRuntimeTestTool("searchCode", [])]);
  const requests: Record<string, unknown>[] = [];
  let callCount = 0;

  const result = await runAgentRuntime({
    userRequest: "Repeat then edit",
    registry,
    runId: "test-runtime-repeated-warning-direct-edit",
    requestCompletion: async (body) => {
      requests.push(body);
      callCount += 1;

      if (callCount <= 2) {
        return {
          choices: [
            {
              message: {
                role: "assistant",
                content: null,
                tool_calls: [
                  {
                    id: `tool-direct-edit-repeat-${callCount}`,
                    type: "function",
                    function: { name: "searchCode", arguments: JSON.stringify({ query: "same-edit-keyword" }) }
                  }
                ]
              }
            }
          ]
        };
      }

      return {
        choices: [{ message: { role: "assistant", content: "Used direct edit warning." } }]
      };
    }
  });

  const warningMessages = requests.flatMap((request) => (request.messages as Array<{ content?: string }> | undefined) || []).filter((message) => message.content?.includes("repeated these tool calls"));
  assert.equal(result.status, "completed");
  assert.equal(warningMessages.some((message) => message.content?.includes("move to proposePatch")), true);
  assert.equal(warningMessages.some((message) => message.content?.includes("direct-edit fallback")), true);
});

test("analysis-only workflow injects its prompt and exposes only read-only tools", async () => {
  const requests: Record<string, unknown>[] = [];
  const workflow = createTaskWorkflow("分析模块依赖", {
    intent: "inspect",
    confidence: 0.9,
    normalizedGoal: "分析模块依赖",
    reason: "test"
  });

  await runAgentRuntime({
    userRequest: "分析模块依赖",
    mode: "act",
    workflow,
    runId: "test-analysis-workflow-tools",
    requestCompletion: async (body) => {
      requests.push(body);
      return { choices: [{ message: { role: "assistant", content: "分析完成" } }] };
    }
  });

  const tools = (requests[0]?.tools as Array<{ function: { name: string } }>).map((tool) => tool.function.name);
  const messages = requests[0]?.messages as Array<{ role: string; content?: string }>;
  assert.equal(tools.includes("proposePatch"), false);
  assert.equal(tools.includes("replaceInFile"), false);
  assert.equal(tools.includes("runCommand"), false);
  assert.match(messages[0]?.content || "", /Task workflow: analysis-only/);
});

test("analysis-only workflow blocks side-effect tools even in a custom registry", async () => {
  let executed = false;
  let callCount = 0;
  const registry = createAgentToolRegistry([createRuntimeTestTool("replaceInFile", { changed: true }, () => { executed = true; })]);
  const workflow = createTaskWorkflow("分析模块依赖", {
    intent: "inspect",
    confidence: 0.9,
    normalizedGoal: "分析模块依赖",
    reason: "test"
  });
  const result = await runAgentRuntime({
    userRequest: "分析模块依赖",
    mode: "act",
    workflow,
    registry,
    runId: "test-analysis-workflow-block",
    requestCompletion: async () => {
      callCount += 1;
      if (callCount === 1) {
        return {
          choices: [{ message: { role: "assistant", content: null, tool_calls: [{ id: "edit-1", type: "function", function: { name: "replaceInFile", arguments: "{}" } }] } }]
        };
      }
      return { choices: [{ message: { role: "assistant", content: "保持只读" } }] };
    }
  });

  assert.equal(executed, false);
  assert.equal(result.messages.some((message) => message.role === "tool" && message.content?.includes("only allows read-only")), true);
});

test("refactor workflow requires impact evidence before editing", async () => {
  let executed = false;
  let callCount = 0;
  const registry = createAgentToolRegistry([createRuntimeTestTool("proposePatch", { patchId: "patch-1" }, () => { executed = true; })]);
  const workflow = createTaskWorkflow("重构任务存储", {
    intent: "edit",
    confidence: 0.9,
    normalizedGoal: "重构任务存储",
    reason: "test"
  });
  const result = await runAgentRuntime({
    userRequest: "重构任务存储",
    workflow,
    registry,
    agentContext: {
      userGoal: "重构任务存储",
      filesRead: ["src/store.ts"],
      searchQueries: [],
      searchResultFiles: [],
      relevantFiles: ["src/store.ts"]
    },
    runId: "test-refactor-workflow-impact",
    requestCompletion: async () => {
      callCount += 1;
      if (callCount === 1) {
        return {
          choices: [{ message: { role: "assistant", content: null, tool_calls: [{ id: "patch-1", type: "function", function: { name: "proposePatch", arguments: "{}" } }] } }]
        };
      }
      return { choices: [{ message: { role: "assistant", content: "先补影响分析" } }] };
    }
  });

  assert.equal(executed, false);
  assert.equal(result.messages.some((message) => message.role === "tool" && message.content?.includes("requires analyzeImpact")), true);
});

test("bugfix workflow requires a reproduction command attempt before editing", async () => {
  let executed = false;
  let callCount = 0;
  const registry = createAgentToolRegistry([createRuntimeTestTool("proposePatch", { patchId: "patch-1" }, () => { executed = true; })]);
  const workflow = createTaskWorkflow("修复登录失败", {
    intent: "diagnose_then_edit",
    confidence: 0.9,
    normalizedGoal: "修复登录失败",
    reason: "test"
  });
  const result = await runAgentRuntime({
    userRequest: "修复登录失败",
    workflow,
    registry,
    agentContext: {
      userGoal: "修复登录失败",
      filesRead: ["src/login.ts"],
      searchQueries: [],
      searchResultFiles: [],
      relevantFiles: ["src/login.ts"],
      commandsRun: []
    },
    runId: "test-bugfix-workflow-reproduction",
    requestCompletion: async () => {
      callCount += 1;
      if (callCount === 1) {
        return {
          choices: [{ message: { role: "assistant", content: null, tool_calls: [{ id: "patch-1", type: "function", function: { name: "proposePatch", arguments: "{}" } }] } }]
        };
      }
      return { choices: [{ message: { role: "assistant", content: "先复现问题" } }] };
    }
  });

  assert.equal(executed, false);
  assert.equal(result.messages.some((message) => message.role === "tool" && message.content?.includes("command attempt")), true);
});
